---

- name: Install packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
     - php5
     - php5-mysql
     - php5-gd
     - php5-cli # for Drush
     - apache2
     - git
     - python-mysqldb # for db task delegation

- name: Enable mod_rewrite
  apache2_module: name=rewrite state=present

- name: Remove default apache2 files
  file:
    dest: /etc/apache2/sites-enabled/000-default.conf
    state: absent

- name: Add Drupal to apache
  template:
    src: drupal.conf.j2
    dest: /etc/apache2/sites-enabled/drupal.conf
    owner: root
    group: root
  notify:
    - restart apache