---

- name: create ELB
  ec2_elb_lb:
    name: drupal-elb
    state: present
    region: "{{ aws_region }}"
    security_group_names:
      - drupal
      - edge
    subnets: "{{ vpc.subnets | map(attribute='id') | list }}"
    listeners:
    - protocol: http
      load_balancer_port: 80
      instance_port: 80
    - protocol: https
      load_balancer_port: 443
      instance_protocol: http
      instance_port: 80
      ssl_certificate_id: "{{ ssl_cert_id }}"
    health_check:
      ping_protocol: http
      ping_port: 80
      ping_path: "/robots.txt"
      response_timeout: 5 # seconds
      interval: 10 # seconds
      unhealthy_threshold: 2
      healthy_threshold: 4
  register: elb