---

- name: RDS subnet group
  rds_subnet_group:
    state: present
    name: "{{ rds_subnet_group_name }}"
    description: drupal-dev rds subnet group
    region: "{{ aws_region }}"
    subnets: "{{ vpc.subnets | map(attribute='id') | list }}"

- name: RDS instance
  rds:
    command: create
    multi_zone: yes
    subnet: "{{ rds_subnet_group_name }}"
    vpc_security_groups: "{{ drupal_group.group_id }}"
    instance_name: drupal-dev
    tags:
      environment: dev
      eole: db
    db_engine: MySQL
    size: 10
    instance_type: "{{ db_instance_type }}"
    username: "{{ db_admin_username }}"
    password: "{{ db_admin_password }}"
    region: "{{ aws_region }}"
  register: rds